#Application properties

deviceSpecifications:
  url: http://www.devicespecifications.com/en

benchmarks:
  urls:
    passRating: http://www.androidbenchmark.net/passmark_chart.html
    CPURating: http://www.androidbenchmark.net/cpumark_chart.html
    memoryRating: http://www.androidbenchmark.net/memmark_chart.html
    diskRating: http://www.androidbenchmark.net/diskmark_chart.html
    2DGraphicsRating: http://www.androidbenchmark.net/g2dmark_chart.html
    3DGraphicsRating: http://www.androidbenchmark.net/g3dmark_chart.html

#Spring properties

spring:
  application:
    name: device-data-crawler

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/device-crawler-dev?useSSL=false
    username: root
    password: mysql
    driverClassName: com.mysql.jdbc.Driver


logging:
  level: INFO
  file: ${user.home}/${spring.application.name}.log
    