#Application properties

deviceSpecifications:
  url: http://www.devicespecifications.com/en

benchmarks:
  urls:
    PassMark: http://www.androidbenchmark.net/passmark_chart.html
    CPUMark: http://www.androidbenchmark.net/cpumark_chart.html
    memoryMark: http://www.androidbenchmark.net/memmark_chart.html
    diskMark: http://www.androidbenchmark.net/diskmark_chart.html
    2DGraphicsMark: http://www.androidbenchmark.net/g2dmark_chart.html
    3DGraphicsMark: http://www.androidbenchmark.net/g3dmark_chart.html

google:
  supportedDevices:
    csv: http://storage.googleapis.com/play_public/supported_devices.csv

deviceProcess:
  nextId: 1

firebase:
  baseUrl: https://device-data-store.firebaseio.com
  
#Spring properties

spring:
  application:
    name: device-data-crawler

  jpa:
    database: device-data
    database-platform: org.unicen.ddcrawler.util.SQLiteDialect
    show-sql: false
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:sqlite:c:/sqlite/device-data.db
    driverClassName: org.sqlite.JDBC

#    url: jdbc:mysql://localhost:3306/device-crawler-dev?useSSL=false
#    username: root
#    password: mysql
#    driverClassName: com.mysql.jdbc.Driver


logging:
  level: INFO
  file: ${user.home}/${spring.application.name}.log
    
    