#General properties

urls:
  deviceSpecifications: http://www.devicespecifications.com/en
  
#Database properties

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: mysql
    driverClassName: com.mysql.jdbc.Driver
