#Application properties

deviceSpecifications:
  url: http://www.devicespecifications.com/en

benchmarks:
  urls:
    passMarkRating: http://www.androidbenchmark.net/passmark_chart.html

#Spring properties

spring:
  application:
    name: device-data-crawler

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/device-crawler-dev?useSSL=false
    username: root
    password: mysql
    driverClassName: com.mysql.jdbc.Driver


logging:
  level: INFO
  file: ${user.home}/${spring.application.name}.log
    