#Application properties

urls:
  deviceSpecifications: http://www.devicespecifications.com/en


#Spring properties

spring:
  application:
    name: device-data-crawler

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/device-crawler-dev
    username: root
    password: mysql
    driverClassName: com.mysql.jdbc.Driver


logging:
  level: INFO
  file: ${java.io.tmpdir}/${spring.application.name}.log
    